/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_wso2_siddhi_pythonapi_threadfix_PyThreadFix */

#ifndef _Included_org_wso2_siddhi_pythonapi_threadfix_PyThreadFix
#define _Included_org_wso2_siddhi_pythonapi_threadfix_PyThreadFix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_wso2_siddhi_pythonapi_threadfix_PyThreadFix
 * Method:    fixThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_wso2_siddhi_pythonapi_threadfix_PyThreadFix_fixThread
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
